"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anakin_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=True),
    sa.Column('credits', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('current_sha256', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=True),
    sa.Column('text_path', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('parse_status', sa.String(length=30), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_documents_current_sha256'), 'documents', ['current_sha256'], unique=False)
    op.create_table('fetch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetcher', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_log_url'), 'fetch_log', ['url'], unique=False)
    op.create_table('hs_master',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('qco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qco_number', sa.String(length=200), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('ministry', sa.Text(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('is_qco', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qco_qco_number'), 'qco', ['qco_number'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('alert_mode', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetcher', sa.String(length=20), nullable=False),
    sa.Column('credits_used', sa.Float(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('raw_path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'sha256')
    )
    op.create_index(op.f('ix_document_versions_document_id'), 'document_versions', ['document_id'], unique=False)
    op.create_table('llm_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('qco_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qco_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('compliance_deadline', sa.Date(), nullable=True),
    sa.Column('exemptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extractor_version', sa.String(length=50), nullable=True),
    sa.Column('raw_extraction', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['qco_id'], ['qco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qco_event_document_id'), 'qco_event', ['document_id'], unique=False)
    op.create_index(op.f('ix_qco_event_qco_id'), 'qco_event', ['qco_id'], unique=False)
    op.create_table('text_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_chunks_document_id'), 'text_chunks', ['document_id'], unique=False)
    op.create_table('watch_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hs_code', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hs_code')
    )
    op.create_index(op.f('ix_watch_codes_user_id'), 'watch_codes', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('watch_code', sa.String(length=8), nullable=False),
    sa.Column('matched_hs_code', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['qco_event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', 'watch_code', 'matched_hs_code')
    )
    op.create_index(op.f('ix_alerts_event_id'), 'alerts', ['event_id'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('qco_hs_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('qco_id', sa.Integer(), nullable=True),
    sa.Column('hs_code', sa.String(length=8), nullable=False),
    sa.Column('hs_level', sa.Integer(), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['qco_event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['qco_id'], ['qco.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qco_hs_map_event_id'), 'qco_hs_map', ['event_id'], unique=False)
    op.create_index('ix_qco_hs_map_prefix', 'qco_hs_map', ['hs_code'], unique=False, postgresql_ops={'hs_code': 'text_pattern_ops'})
    op.create_index(op.f('ix_qco_hs_map_qco_id'), 'qco_hs_map', ['qco_id'], unique=False)
    op.create_table('qco_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_standard', sa.String(length=200), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['qco_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qco_product_event_id'), 'qco_product', ['event_id'], unique=False)
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['qco_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_queue_document_id'), 'review_queue', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_queue_document_id'), table_name='review_queue')
    op.drop_table('review_queue')
    op.drop_index(op.f('ix_qco_product_event_id'), table_name='qco_product')
    op.drop_table('qco_product')
    op.drop_index(op.f('ix_qco_hs_map_qco_id'), table_name='qco_hs_map')
    op.drop_index('ix_qco_hs_map_prefix', table_name='qco_hs_map', postgresql_ops={'hs_code': 'text_pattern_ops'})
    op.drop_index(op.f('ix_qco_hs_map_event_id'), table_name='qco_hs_map')
    op.drop_table('qco_hs_map')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_event_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_watch_codes_user_id'), table_name='watch_codes')
    op.drop_table('watch_codes')
    op.drop_index(op.f('ix_text_chunks_document_id'), table_name='text_chunks')
    op.drop_table('text_chunks')
    op.drop_index(op.f('ix_qco_event_qco_id'), table_name='qco_event')
    op.drop_index(op.f('ix_qco_event_document_id'), table_name='qco_event')
    op.drop_table('qco_event')
    op.drop_table('llm_cache')
    op.drop_index(op.f('ix_document_versions_document_id'), table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_table('users')
    op.drop_index(op.f('ix_qco_qco_number'), table_name='qco')
    op.drop_table('qco')
    op.drop_table('hs_master')
    op.drop_index(op.f('ix_fetch_log_url'), table_name='fetch_log')
    op.drop_table('fetch_log')
    op.drop_index(op.f('ix_documents_current_sha256'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('anakin_ledger')
    # ### end Alembic commands ###
